# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StufffID', models.IntegerField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=16)),
                ('house', models.CharField(max_length=16)),
                ('address1', models.CharField(max_length=16)),
                ('address2', models.CharField(max_length=16)),
                ('postcode', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.IntegerField(max_length=16, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=16)),
                ('Price', models.CharField(max_length=16)),
                ('Description', models.CharField(max_length=16)),
            ],
        ),
    ]
