# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.IntegerField(max_length=16, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=16)),
                ('Price', models.CharField(max_length=16)),
                ('Description', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Records',
        ),
        migrations.AddField(
            model_name='basket',
            name='StuffID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Products'),
        ),
    ]
