# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='StufffID',
            new_name='StuffID_id',
        ),
    ]
