# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20170322_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='StuffID_id',
            new_name='StuffID',
        ),
    ]
