# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20170322_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paymentmethodid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='billingaddressid',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='userid',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Paymentmethod',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
