# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20170322_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='sDescription',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='sName',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='sPrice',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
