# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20170322_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(blank=True, db_column='Description', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(blank=True, db_column='Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.TextField(blank=True, db_column='Price', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.IntegerField(db_column='ProductId', primary_key=True, serialize=False),
        ),
    ]
