# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20170322_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='productid',
        ),
        migrations.AddField(
            model_name='basket',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='StuffID_id',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.IntegerField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
