# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20170322_1932'),
        ('ecommerce', '0006_auto_20170322_2003'),
    ]

    operations = [
    ]
