# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_merge_20170322_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userid',
        ),
        migrations.AlterField(
            model_name='basket',
            name='StuffID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='Username', max_length=255, primary_key=True, serialize=False),
        ),
    ]
