# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.AutoField(db_column='OrderId', primary_key=True, serialize=False),
        ),
    ]
