# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20170322_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.TextField(blank=True, db_column='Image', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='addressid',
            field=models.AutoField(db_column='AddressId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='paymentmethodid',
            field=models.AutoField(db_column='PaymentMethodId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.AutoField(db_column='ProductId', primary_key=True, serialize=False),
        ),
    ]
