# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20170323_0016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
